"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    Object.defineProperty(o, k2, { enumerable: true, get: function() { return m[k]; } });
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
var fs_1 = require("fs");
var ts = __importStar(require("typescript"));
var command_line_args_1 = __importDefault(require("command-line-args"));
var command_line_usage_1 = __importDefault(require("command-line-usage"));
var lib_1 = require("./lib");
var output = {};
var optionDefinitions = [
    {
        name: 'file',
        alias: 'f',
        type: String,
    },
    { name: 'interfaces', alias: 'i', type: String, multiple: true },
    { name: 'help', alias: 'h', type: Boolean },
    { name: 'fixed', alias: 'x', type: Boolean },
    { name: 'outFile', alias: 'o', type: String },
];
var instructions = [
    {
        content: 'mock-type',
        raw: true,
    },
    {
        header: '',
        content: 'Generates fake data from TypeScript interfaces via Faker',
    },
    {
        header: 'Options',
        optionList: [
            {
                name: 'interfaces',
                typeLabel: 'example: --interfaces "Person" "User"',
                description: 'Optional list of interfaces to mock, right now only support one interface',
            },
            {
                name: 'file',
                typeLabel: 'example: ./model.ts',
                description: 'Interface file to generate fake data from',
            },
            {
                name: 'outdir',
                typeLabel: 'example ./mock',
                description: 'Default directory will be mock under current path'
            },
            {
                name: 'help',
                description: 'Print this usage guide.',
            }
        ],
    },
];
function isWelcomeMessageNeeded(options) {
    if (!options || !options.file || options.help) {
        return true;
    }
    return false;
}
function showWelcomeMessage() {
    var usage = command_line_usage_1.default(instructions);
    console.log(usage);
}
function writeToFile(options) {
    var commentLine = "// THIS IS GENERATED BY TS-MOCK, DON'T EDIT IT \r\n";
    var data = commentLine + "export default " + JSON.stringify(output, null, 2);
    fs_1.writeFile(options.outFile, data, function (error) {
        if (error) {
            console.log(error);
        }
    });
}
function main() {
    var options = command_line_args_1.default(optionDefinitions);
    if (isWelcomeMessageNeeded(options)) {
        showWelcomeMessage();
        return;
    }
    var sourceFile = ts.createSourceFile(options.file, fs_1.readFileSync(options.file).toString(), ts.ScriptTarget.ES2015, true);
    lib_1.processFile(sourceFile, options, output);
    console.log(JSON.stringify(output));
    if (options.outFile) {
        writeToFile(options);
    }
}
main();
