"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
// THIS IS GENERATED BY TS-MOCK, DON'T EDIT IT 
exports.default = [
    {
        name: 'Blanditiis aut ratione temporibus impedit aut sit '
    },
    {
        name: 'Inventore aut minima inventore tempora ea et.\nIpsa'
    },
    {
        name: 'Voluptates et reiciendis ea est itaque qui expedit'
    }
];
